#!/bin/bash

# Quick Demo Script for KPBU Dashboard
echo "🎯 KPBU Dashboard Quick Demo"
echo "============================"

echo "📝 Demo Instructions:"
echo ""
echo "1. 👤 FILL INVESTOR PROFILE:"
echo "   - Name: 'Demo Investor'"
echo "   - Risk: 'Moderat'"
echo "   - Sectors: Air & Sanitasi, Jalan & Jembatan, Kesehatan"
echo "   - Horizon: 'Jangka Panjang'"
echo "   - Size: 'Besar'"
echo ""
echo "2. 💾 CLICK 'Save Profile' to get recommendations"
echo ""
echo "3. 🔮 TEST RISK PREDICTION:"
echo "   - Project: 'Demo Jalan Tol'"
echo "   - Sector: 'Jalan dan Jembatan'"
echo "   - Status: 'Konstruksi'"
echo "   - Duration: 25 years"
echo "   - Investment: 5.0 trillion"
echo ""
echo "4. 🚀 START CHAT:"
echo "   - Click 'Start Investment Chat'"
echo "   - Ask: 'Jelaskan keunggulan proyek jalan tol untuk investasi'"
echo "   - Try: 'Bandingkan risiko sektor infrastruktur vs energi'"
echo ""
echo "5. 🔧 TEST FOOTER BUTTONS:"
echo "   - Dataset Stats"
echo "   - Test Gemini API"
echo "   - Cleanup Sessions"
echo ""
echo "📋 Expected Features:"
echo "✅ Markdown styling in chat bubbles"
echo "✅ 'Agent Typing' indicator with animation"
echo "✅ User name display above chat bubbles"
echo "✅ Neutral colors for dark/light mode"
echo "✅ Responsive chat container with scroll"
echo "✅ Professional message styling"
echo ""
echo "🌐 URLs:"
echo "  Dashboard: http://localhost:8501"
echo "  API Docs:  http://localhost:8000/docs"
echo ""
echo "📱 Mobile Responsive: Test on different screen sizes"
echo "🎨 Theme Toggle: Try switching Streamlit theme in settings"
echo ""
echo "============================"
echo "Ready to demo! 🚀"
